module VerifyExamples.Algorithm.FromString1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Algorithm exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#fromString: \n\n    fromString \"\"\n    --> Err EmptyAlgorithm" <|
        \() ->
            Expect.equal
                (
                fromString ""
                )
                (
                Err EmptyAlgorithm
                )