module VerifyExamples.Algorithm.Inverse0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Algorithm exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#inverse: \n\n    Result.map inverse <| fromString \"UB'\"\n    --> fromString \"BU'\"" <|
        \() ->
            Expect.equal
                (
                Result.map inverse <| fromString "UB'"
                )
                (
                fromString "BU'"
                )