module VerifyExamples.Algorithm.ReverseAppend0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Algorithm exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#reverseAppend: \n\n    Result.map2 reverseAppend (fromString \"U\") (fromString \"B'\")\n    --> fromString \"B'U\"" <|
        \() ->
            Expect.equal
                (
                Result.map2 reverseAppend (fromString "U") (fromString "B'")
                )
                (
                fromString "B'U"
                )