module VerifyExamples.Algorithm.ToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Algorithm exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toString: \n\n    fromTurnList\n        [ Turn U Halfway CounterClockwise\n        , Turn F OneQuarter Clockwise\n        ]\n        |> toString\n    --> \"U2' F\"" <|
        \() ->
            Expect.equal
                (
                fromTurnList
                    [ Turn U Halfway CounterClockwise
                    , Turn F OneQuarter Clockwise
                    ]
                    |> toString
                )
                (
                "U2' F"
                )