module VerifyExamples.PLL.All0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import List.Nonempty







spec0 : Test.Test
spec0 =
    Test.test "#all: \n\n    -- All the PLLs are there!\n    List.Nonempty.length all\n    --> 21" <|
        \() ->
            Expect.equal
                (
                -- All the PLLs are there!
                List.Nonempty.length all
                )
                (
                21
                )