module VerifyExamples.PLL.GetAlgorithm0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#getAlgorithm: \n\n    getAlg referenceAlgs Y\n    --> referenceAlgs.y" <|
        \() ->
            Expect.equal
                (
                getAlg referenceAlgs Y
                )
                (
                referenceAlgs.y
                )