module VerifyExamples.PLL.ReferenceAlgorithms11 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import PLL exposing (..)
import Algorithm







spec11 : Test.Test
spec11 =
    Test.test "#referenceAlgorithms: \n\n    Algorithm.fromString \"R' U' R B2 D (L' U L U' L) D' B2\"\n    --> Ok referenceAlgorithms.gb" <|
        \() ->
            Expect.equal
                (
                Algorithm.fromString "R' U' R B2 D (L' U L U' L) D' B2"
                )
                (
                Ok referenceAlgorithms.gb
                )