module VerifyExamples.AUF.FromString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AUF exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#fromString: \n\n    fromString \"U B\"\n    --> Err InvalidAUFAlgorithm" <|
        \() ->
            Expect.equal
                (
                fromString "U B"
                )
                (
                Err InvalidAUFAlgorithm
                )