module VerifyExamples.AUF.FromString2 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AUF exposing (..)







spec2 : Test.Test
spec2 =
    Test.test "#fromString: \n\n    fromString \"U'\"\n    --> Ok CounterClockwise" <|
        \() ->
            Expect.equal
                (
                fromString "U'"
                )
                (
                Ok CounterClockwise
                )