module VerifyExamples.AUF.FromString1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AUF exposing (..)







spec1 : Test.Test
spec1 =
    Test.test "#fromString: \n\n    fromString \"\"\n    --> Ok None" <|
        \() ->
            Expect.equal
                (
                fromString ""
                )
                (
                Ok None
                )