module VerifyExamples.AUF.ToString0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import AUF exposing (..)







spec0 : Test.Test
spec0 =
    Test.test "#toString: \n\n    toString Halfway\n    --> \"U2\"" <|
        \() ->
            Expect.equal
                (
                toString Halfway
                )
                (
                "U2"
                )